services:
  proxy:
    build: ./proxy
    image: webcorvus/better-vite-template-proxy:latest
    container_name: better-vite-template-proxy
    ports:
      - 8080:80
    env_file:
      - ./proxy/.env
    depends_on:
      api:
        condition: service_healthy
      app:
        condition: service_healthy
    networks:
      - public
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80/healthcheck || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 20
      start_period: 30s

  app:
    build: ./app
    image: webcorvus/better-vite-template-app:latest
    container_name: better-vite-template-app
    environment:
      - NODE_ENV=production
    env_file:
      - ./app/.env
    depends_on:
      api:
        condition: service_healthy
    networks:
      - public
    restart: unless-stopped
    healthcheck:
      test:
        ["CMD-SHELL", "curl -sf http://localhost:5173/healthcheck || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s

  api:
    build: ./api
    image: webcorvus/better-vite-template-api:latest
    container_name: better-vite-template-api
    env_file:
      - ./api/.env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - public
      - private
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "python /api/healthcheck.py"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

  db:
    build: ./db
    image: webcorvus/better-vite-template-db:latest
    container_name: better-vite-template-db
    env_file:
      - ./db/.env
    networks:
      - private
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 20s

networks:
  public:
    driver: bridge
  private:
    driver: bridge
