FROM node:22.18.0-alpine

RUN apk add --no-cache libc6-compat bash curl
RUN npm install -g serve

WORKDIR /app

COPY entrypoint.sh /entrypoint.sh
COPY package*.json tsconfig*.json ./
COPY . .

RUN npm ci
RUN npm run build

RUN addgroup --system --gid 1001 nodejs && \
    adduser --system --uid 1001 vitejs

RUN chmod u+x /entrypoint.sh
RUN chown -R vitejs:nodejs /app

USER vitejs

EXPOSE 5173

ENTRYPOINT [ "/entrypoint.sh" ]